export const blogList = [
  {
    id: 1,
    title: 'Unlocking Your Potential: The Power of Having a System as a Software Developer ',
    category: 'Developer',
    subCategory: ['learning', 'dev', 'web'],
    description:
    "Unlock your potential as a software developer! Discover the power of having a system to navigate complex projects, boost productivity, foster collaboration, and embrace continuous learning ",
    authorName:'Aaquib Ali' ,
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'July 9, 2023',
    cover: '/assets/images/blog10.png',
    redirectionUrl:"https://www.linkedin.com/pulse/unlocking-your-potential-power-having-system-software-aaquib-ali",
  },
    {
      id: 2,
      title: '10 Must Have VS Code Extension For Web Developers',
      category: 'Developer',
      subCategory: ['top10', 'vscode', 'web'],
      description:
      "Take your web dev skills to new heights with these 10 must-have VSCode extensions! Boost productivity, streamline your workflow, and create amazing projects. ",
      authorName:'Aaquib Ali' ,
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'July 2, 2023',
      cover: '/assets/images/blog9.png',
      redirectionUrl:"https://www.linkedin.com/pulse/10-must-have-vscode-extensions-web-development-aaquib-ali?utm_source=share&utm_medium=member_android&utm_campaign=share_via",
    },
    {
      id: 3,
      title: '10 Programming Principles Every Software Developer Should Know',
      category: 'Developer',
      subCategory: ['Tips', 'programing', 'skill'],
      description:
      "Want to take your coding skills to the next level? Look no further! I've just stumbled upon an incredible article that reveals the 10 game-changing programming principles.. ",
      authorName:'Aaquib Ali' ,
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 24, 2023',
      cover: '/assets/images/blog8.png',
      redirectionUrl:"https://www.linkedin.com/pulse/10-programming-principles-every-software-developer-should-aaquib-ali?utm_source=share&utm_medium=member_android&utm_campaign=share_via",

    },
    {
      id: 4,
      title: '9 Ways To Improve Your Writing Skills',
      category: 'Writting',
      subCategory: ['Tips', 'Writting', 'skill'],
      description:
      "Are you looking to enhance your writing skills and become a more effective communicator? ",
      authorName:'Aaquib Ali' ,
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 20, 2023',
      cover: '/assets/images/blog7.png',
      redirectionUrl:"https://www.linkedin.com/pulse/9-ways-improve-your-writing-skills-aaquib-ali?utm_source=share&utm_medium=member_android&utm_campaign=share_via",
    },
    {
      id: 5,
      title: 'Unveiling the World of NFTs: A Comprehensive Guide ',
      category: 'NFT',
      subCategory: ['web3', 'art', 'nft'],
      description:
      "Exploring the world of NFTs: from their definition and technology to their impact on industries and notable examples. Discover the revolution of unique digital assets",
      authorName: 'Aaquib Ali',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 10, 2023',
      cover: '/assets/images/blog1.png',
      redirectionUrl:"https://www.linkedin.com/pulse/unveiling-world-nfts-comprehensive-guide-aaquib-ali?utm_source=share&utm_medium=member_android&utm_campaign=share_via",
    },
    {
      id: 6,
      title: 'Coding Efficiency Unleashed: 10 ChatGPT Hacks for Developers',
      category: 'AI',
      subCategory: ['chatgpt', 'ai', 'developer'],
      description:
        "Unleash ChatGPT's power to optimize your coding workflow. Discover 10 game-changing commands that will save time, troubleshoot, generate code snippets, and enhance your productivity as a developer.",
      authorName: 'Aaquib Ali',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'June 03, 2023',
      cover: '/assets/images/blog2.png',
      redirectionUrl:"https://www.linkedin.com/pulse/coding-efficiency-unleashed-10-chatgpt-hacks-developers-aaquib-ali?utm_source=share&utm_medium=member_android&utm_campaign=share_via", 
    },
    {
      id: 7,
      title: 'ChatGPT vs Bard: Which chatbot is better?',
      category: 'AI',
      subCategory: ['chatgpt', 'ai', 'brad'],
      description:
        "A comparison of AI chatbots in terms of instruction, understanding, reasoning, creativity, and speed. Discover their strengths and weaknesses in this insightful article.",
      authorName: 'Aaquib Ali',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'May 27, 2023',
      cover: '/assets/images/blog3.png',
      redirectionUrl:"https://www.linkedin.com/pulse/chatgpt-vs-brad-which-chatbot-better-aaquib-ali?utm_source=share&utm_medium=member_android&utm_campaign=share_via",
    },
    {
      id: 8,
      title: 'Top 5 in Demand Programming Languages to learn in 2023',
      category: 'Programming',
      subCategory: ['developer', 'programming', 'language'],
      description:
        "Discover the top 5 in-demand programming languages for 2022. From JavaScript to Solidity, explore their learning duration, job opportunities, and features in this insightful article.",
      authorName: 'Aaquib Ali',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'May 20, 2023',
      cover: '/assets/images/blog4.png',
      redirectionUrl:"https://www.linkedin.com/pulse/top-5-demand-programming-languages-learn-2023-aaquib-ali?utm_source=share&utm_medium=member_android&utm_campaign=share_via",
    },
    {
      id: 9,
      title: 'A complete Beginner’s guide — Web 3.0',
      category: 'Web3',
      subCategory: ['guide', 'begainner', 'programming'],
      description:
        "Explore the evolution of the web from Web 1.0 to Web 3.0 in this informative article. Discover the features, differences, and unique characteristics of each phase, including the potential of Web 3.0 to revolutionize our online experiences.",
      authorName: 'Aaquib Ali',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'May 13, 2023',
      cover: '/assets/images/blog5.png',
      redirectionUrl:"https://www.linkedin.com/pulse/complete-beginners-guide-web-30-aaquib-ali?utm_source=share&utm_medium=member_android&utm_campaign=share_via",
    },
    {
      id: 10,
      title: 'Web3: An Introduction to the Decentralized Future of the Internet',
      category: 'Web3',
      subCategory: ['language', 'decentralized', 'programming'],
      description:
        "Discover the decentralized world of web3 and how it revolutionizes online interactions. Explore blockchain, cryptocurrencies, and smart contracts in this informative article and join The VerSiton community for support and resources.",
      authorName: 'Aaquib Ali',
      authorAvatar: '/assets/images/author.jpg',
      createdAt: 'May 06, 2023',
      cover:
        '/assets/images/blog6.png',
        redirectionUrl:"https://www.linkedin.com/pulse/web3-introduction-decentralized-future-internet-aaquib-ali?utm_source=share&utm_medium=member_android&utm_campaign=share_via",
    },
  ];
  
